{% set version = '3.4-6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rfoc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RFOC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RFOC/RFOC_{{ version }}.tar.gz
  sha256: 0dfa237f4d04eb9a2718942b4d7ed9538fc5f89e3cbaa5a34a4fd1bc6fe54533

build:
  merge_build_host: True  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-geomap
    - r-mass
    - r-rpmg
    - r-rseis
    - r-splancs
  run:
    - r-base
    - r-geomap
    - r-mass
    - r-rpmg
    - r-rseis
    - r-splancs

test:
  commands:
    - $R -e "library('RFOC')"           # [not win]
    - "\"%R%\" -e \"library('RFOC')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RFOC
  license: GPL-2.0-or-later
  summary: Graphics for statistics on a sphere, as applied to geological fault data, crystallography,
    earthquake focal mechanisms, radiation patterns, ternary plots and geographical/geological
    maps.  Non-double couple plotting of focal spheres and source type maps are included
    for statistical analysis of moment tensors.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RFOC
# Type: Package
# Title: Graphics for Spherical Distributions and Earthquake Focal Mechanisms
# Version: 3.4-6
# Date: 2018-01-17
# Depends: R (>= 3.1.0)
# Imports: RPMG, GEOmap, RSEIS, MASS, splancs
# Authors@R: c(person(given="Jonathan M.", family="Lees", role = c("aut", "cre"),email = "jonathan.lees@unc.edu"), person("Keehoon", "Kim", role = "ctb"))
# Author: Jonathan M. Lees [aut, cre], Keehoon Kim [ctb]
# Maintainer: Jonathan M. Lees <jonathan.lees@unc.edu>
# Description: Graphics for statistics on a sphere, as applied to geological fault data, crystallography, earthquake focal mechanisms, radiation patterns, ternary plots and geographical/geological maps.  Non-double couple plotting of focal spheres and source type maps are included for statistical analysis of moment tensors.
# License: GPL (>= 2)
# Packaged: 2018-01-17 20:42:42 UTC; lees
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2018-01-18 11:13:23 UTC
