appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: MYKq/Zi1f/XnzI2mGmbTGGE5TqvYWVmH6M/Fo/DXndicKlgD3gJolqKBAJ3SOM441DZG4esFwA0uedUjZp4TyAD7FlxpRK8Qf9A1/nzj7ZTPuWe6k2znWCkXoxzPXfOxkdQMIcTxz6rRDK8sd3VJeg+4F34qj4y9rtz+HT4oU1J9qrRuCkfUs1EJ9LSvfc57qWdTH5sdw/l8d7W190ql8hzg5cGYytXQeS7HtmmjF4o1Q24dZRkIVIjzarmtPvst4SURsCPzbCXjzrDhYmBhtAm0c25U3TNQnY5uf+HsIg2E4CjqpmVAEBBEi+WiFepv4YTUhoI8HUVj+EuBf7BQY2a+9dl2OF2l3kVmD2Xco+0gFMtaKX2Sq8PFuG4Hht2roGMDmRYAxIEuMV6AGFuPhZIg0RGLcr313SKSRuDMAh97gS9YN4r4pQoCkzLAkWGNeaCFOb5Duw9D9S5MOa0PiyLECV0Ap3fJMpz0nv0fFgg7Y/yIHooaiIVSUfdbbki6mXOzgyiJQZFIHrUKEcvjYIB5ifSflC+S5ZIJ9XajzbLYmB0h2L/4RNrWQbJCT+H+5+f+9iw0MxNWa7SXln3eBZ8BE3wagAXU4IjC0Bx2qSsx+nYA1180lxtUGY+BfQmg94TgNeJG4x5fux7z4ewlSzz1Noe/3IIajHYoWkI1xJ0=
conda_forge_output_validation: false
